GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ 
Content-type: application/json

{
    "content": "sample",
    "important": false
}

###
POST http://localhost:3001/api/login 
Content-type: application/json

{
    "username": "Khanh", 
    "password": "khanh060506"
}
